# Configuracion de conexion a la base de datos
# Ajusta usuario y contrasena con los que ya usas en MySQL Workbench para "pequegestion"

spring.datasource.url=jdbc:mysql://localhost:3306/pequegestion?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Alejandro20
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate crea/actualiza automaticamente las tablas segun las entidades (@Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
